name: Docker

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.WORTOGETHERUSER }}
          password: ${{ secrets.WORTOGETHERPASSWORD }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.WORTOGETHERUSER }}/worktogether:${{github.sha}}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy-test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.IPDEVOPS }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEYSSHDEVOPS }}
        script: |
          sed -i "s|\(worktogether:\).*|\1${{github.sha}}|" docker-compose-test.yml
          docker compose -f docker-compose-test.yml -p worktogether_test up -d

  
  cypress-test:
    needs: deploy-test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: test
        uses: cypress-io/github-action@v6
        with:
          config: baseUrl=http://${{ secrets.IPDEVOPS }}:81        
      - name: deleteEnvTest
        uses: appleboy/ssh-action@v1.0.3
        if: always()
        with:
          host: ${{ secrets.IPDEVOPS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEYSSHDEVOPS }}
          script: |
            docker compose -p worktogether_test down
            
  deploy:
    needs: cypress-test
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.IPDEVOPS }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEYSSHDEVOPS }}
        script: |
          sed -i "s|\(worktogether:\).*|\1${{github.sha}}|" docker-compose.yml
          docker compose up -d

